FROM golang:1.25.4-alpine3.22

WORKDIR /yellowbook/backend

ADD go.mod go.sum /yellowbook/backend//

RUN go mod download && go install github.com/air-verse/air && go install github.com/swaggo/swag/cmd/swag@latest

ADD . /yellowbook/backend/

EXPOSE 8088

ENV PATH="/go/bin:${PATH}"

CMD [ "air" ]