FROM golang:1.25.4-alpine3.22 AS base

WORKDIR /yellowbook/backend

ADD ./backend/go.mod ./backend/go.sum /yellowbook/backend/

RUN go mod download

ADD ./backend /yellowbook/backend/

FROM base as build

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o binary

FROM base AS dev

RUN go install github.com/air-verse/air && \
    go install github.com/swaggo/swag/cmd/swag@latest

ENV PATH="/go/bin:${PATH}"

CMD ["air"]

FROM base AS prod

WORKDIR /yellowbook/production

COPY --from=build /yellowbook/backend/binary ./binary

EXPOSE 8085

CMD ["/yellowbook/production/binary"]
