services:
  backend:
    build: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./backend:/server/golang
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0.40
    ports:
      - "3308:${MYSQL_DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
    volumes:
      - ./project-data/mysql:/var/lib/mysql
    restart: always
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8084:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
    restart: always
    env_file:
      - .env

  jenkins:
    image: jenkins:2.60.3-alpine
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./project-data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: ${JENKINS_USER}

networks:
  default:
    driver: bridge
